In [1]:
!pip install pandas openpyxl bcrypt

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting bcrypt
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 26.1 MB/s  0:00:00m0:00:010:01
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl (278 kB)
Downloading numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 41.6 MB/s  0:00:006m0:00:01
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: numpy, et-xmlfile, bcrypt, pandas, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [openpyxl]4/5 [openpyxl]
Successfully installed bcrypt-5.0.0 et-xmlfile-2.0.0 numpy-2.5.0 openpyxl-3.1.5 pandas-3.0.3

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip

In [2]:
import pandas as pd
import bcrypt

In [3]:
df=pd.read_csv("voters_jude.csv")
df.head()

    lastName         firstName voter_id  password    class    photo
0     AKELLO   JACKINE PAMELLA    S1001      1001  S1_EAST  non.jpg
1   ATUGONZA     MARIA DAPHINE    S1002      1002  S1_EAST  non.jpg
2    BABIRYE  ROLINDA NAJJINGO    S1003      1003  S1_EAST  non.jpg
3  BABYESIZA             DAVID    S1004      1004  S1_EAST  non.jpg
4    BUKIRWA            JULIET    S1005      1005  S1_EAST  non.jpg

In [4]:
def hash_password(password):
    password = str(password).strip()
    hashed = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
    return hashed.decode('utf-8')

df['password'] = df['password'].apply(hash_password)

In [5]:
df.head()

,lastName,firstName,voter_id,password,class,photo
0,AKELLO,JACKINE PAMELLA,S1001,$2b$12$YjXMGL/6.yfxya38sCwYmu8vn/FG/EJrvGKw17e...,S1_EAST,non.jpg
1,ATUGONZA,MARIA DAPHINE,S1002,$2b$12$mJEduFi4vuucQycImJQJDeNumTsIMAO4iEGfakO...,S1_EAST,non.jpg
2,BABIRYE,ROLINDA NAJJINGO,S1003,$2b$12$JcTALtWFjpl/AaLKpjF4ou5f6gOdbFg/wADbb7j...,S1_EAST,non.jpg
3,BABYESIZA,DAVID,S1004,$2b$12$4KFH4gXBLe2T49cG0YBhD.D8/W3gv4FfbwDZ.K8...,S1_EAST,non.jpg
4,BUKIRWA,JULIET,S1005,$2b$12$tUqujY76y29Ju20YVpljsOp.bI9we2Qw1Q7p5mA...,S1_EAST,non.jpg

In [6]:
df.to_csv("voters_hashed.csv", index=False)